server:
  port: 8765
spring:
  application:
    name: eureka-provider
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://jerry:jerry2022@localhost:8761/eureka/